### ISSUE TITLE
Setting not defined

### ISSUE THREAD

**Issue by breussf** [FRBNY-DSGE/rstarBrookings2017#1]
When running the file "spec1010_20_2016Q3_1223.jl" one gets the error message: "LoadError: UndefVarError: Setting not defined"
(refering to line 19 of the file).
Why?
I am running the file in Juli1 1.7.1. Maybe the program runs only in earlier versions?
Fritz

**Comment by pranay-gundam** [comment]
Hi @breussf, sorry for coming back to this issue so late. There have been a few switches in the people managing this repository that has caused a few issues to get lost in the weeds. Try running the code on Julia v1.5.
